package digital.dispatch.TaxiLimoNewUI;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import digital.dispatch.TaxiLimoNewUI.DBAddress;

import digital.dispatch.TaxiLimoNewUI.DBAddressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBAddressDaoConfig;

    private final DBAddressDao dBAddressDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBAddressDaoConfig = daoConfigMap.get(DBAddressDao.class).clone();
        dBAddressDaoConfig.initIdentityScope(type);

        dBAddressDao = new DBAddressDao(dBAddressDaoConfig, this);

        registerDao(DBAddress.class, dBAddressDao);
    }
    
    public void clear() {
        dBAddressDaoConfig.getIdentityScope().clear();
    }

    public DBAddressDao getDBAddressDao() {
        return dBAddressDao;
    }

}
