package digital.dispatch.TaxiLimoNewUI;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBADDRESS.
 */
public class DBAddress {

    private Long id;
    private String unit;
    private String streetName;
    private String houseNumber;
    private String district;
    private String province;
    private String country;
    private String nickName;
    private Double latitude;
    private Double longitude;
    private Boolean isFavoriate;
    private String fullAddress;

    public DBAddress() {
    }

    public DBAddress(Long id) {
        this.id = id;
    }

    public DBAddress(Long id, String unit, String streetName, String houseNumber, String district, String province, String country, String nickName, Double latitude, Double longitude, Boolean isFavoriate, String fullAddress) {
        this.id = id;
        this.unit = unit;
        this.streetName = streetName;
        this.houseNumber = houseNumber;
        this.district = district;
        this.province = province;
        this.country = country;
        this.nickName = nickName;
        this.latitude = latitude;
        this.longitude = longitude;
        this.isFavoriate = isFavoriate;
        this.fullAddress = fullAddress;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getStreetName() {
        return streetName;
    }

    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    public String getHouseNumber() {
        return houseNumber;
    }

    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Boolean getIsFavoriate() {
        return isFavoriate;
    }

    public void setIsFavoriate(Boolean isFavoriate) {
        this.isFavoriate = isFavoriate;
    }

    public String getFullAddress() {
        return fullAddress;
    }

    public void setFullAddress(String fullAddress) {
        this.fullAddress = fullAddress;
    }

}
