package digital.dispatch.TaxiLimoNewUI;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBCREDIT_CARD.
 */
public class DBCreditCard implements Serializable{

    private Long id;
    private String first4CardNum;
    private String last4CardNum;
    private String holderName;
    private String expiryMonth;
    private String expiryYear;
    private String zip;
    private String nickName;
    private String token;
    private String cardBrand;

    public DBCreditCard() {
    }

    public DBCreditCard(Long id) {
        this.id = id;
    }

    public DBCreditCard(Long id, String first4CardNum, String last4CardNum, String holderName, String expiryMonth, String expiryYear, String zip, String nickName, String token, String cardBrand) {
        this.id = id;
        this.first4CardNum = first4CardNum;
        this.last4CardNum = last4CardNum;
        this.holderName = holderName;
        this.expiryMonth = expiryMonth;
        this.expiryYear = expiryYear;
        this.zip = zip;
        this.nickName = nickName;
        this.token = token;
        this.cardBrand = cardBrand;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirst4CardNum() {
        return first4CardNum;
    }

    public void setFirst4CardNum(String first4CardNum) {
        this.first4CardNum = first4CardNum;
    }

    public String getLast4CardNum() {
        return last4CardNum;
    }

    public void setLast4CardNum(String last4CardNum) {
        this.last4CardNum = last4CardNum;
    }

    public String getHolderName() {
        return holderName;
    }

    public void setHolderName(String holderName) {
        this.holderName = holderName;
    }

    public String getExpiryMonth() {
        return expiryMonth;
    }

    public void setExpiryMonth(String expiryMonth) {
        this.expiryMonth = expiryMonth;
    }

    public String getExpiryYear() {
        return expiryYear;
    }

    public void setExpiryYear(String expiryYear) {
        this.expiryYear = expiryYear;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getCardBrand() {
        return cardBrand;
    }

    public void setCardBrand(String cardBrand) {
        this.cardBrand = cardBrand;
    }

}
