package digital.dispatch.TaxiLimoNewUI;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBPREFERENCE.
 */
public class DBPreference {

    private Long id;
    private String country;
    private String city;
    private String region;
    private String state;
    private String destId;
    private String companyName;
    private String img;
    private String attributeList;
    private String description;

    public DBPreference() {
    }

    public DBPreference(Long id) {
        this.id = id;
    }

    public DBPreference(Long id, String country, String city, String region, String state, String destId, String companyName, String img, String attributeList, String description) {
        this.id = id;
        this.country = country;
        this.city = city;
        this.region = region;
        this.state = state;
        this.destId = destId;
        this.companyName = companyName;
        this.img = img;
        this.attributeList = attributeList;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getDestId() {
        return destId;
    }

    public void setDestId(String destId) {
        this.destId = destId;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getAttributeList() {
        return attributeList;
    }

    public void setAttributeList(String attributeList) {
        this.attributeList = attributeList;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
